# syntax=docker/dockerfile:1
FROM node:20-alpine AS base
WORKDIR /app
COPY package.json package-lock.json ./
COPY libs ./libs
COPY apps/api ./apps/api
COPY tsconfig.json ./
RUN npm ci --workspace=apps/api --include-workspace-root

FROM base AS runner
ENV NODE_ENV=production
ENV PORT=3000
EXPOSE 3000
CMD ["npx", "tsx", "apps/api/src/main.ts"]
